version: '3.4'
services:
  database:
    image: mssql/db
    build:
      context: .
      dockerfile: data/Dockerfile
    ports:
     - "1433:1433"
  cardproducer:
    image:  toyin/cardproducer:mint
    ports:
      - "8082:8082"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8082"
      DATABASESERVER_PORT:     1433
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      KAFKASERVER_PORT:    "9092"

  cardconsumer:
    image:  toyin/cardconsumer:mint
    ports:
      - "8083:8083"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8083"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      KAFKASERVER_PORT:    "9092"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafkaserver:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"