version: '3.4'
services:
  database:
      image: mssql/db
      build:
        context: .
        dockerfile: data/Dockerfile
      ports:
       - "1433:1433"
  cardproducer:
      image:  cardproducer:mint
      ports:
        - "8082:8082"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8082"
        ES_PORT:           9200
        DATABASESERVER_PORT:     1433
        KAFKASERVER_URI: "kafkaserver"
        ZKSERVER_URI: "kafkaserver"
        KAFKASERVER_PORT:    "2181"

  kafkaserver:
      image: spotify/kafka
      ports:
        - 2181:2181
        - 9092:9092
