spring:
  application:
    name: cardconsumer
    profiles:
      active:
        default

  kafka:
      consumer:
        group-id: card-group
        auto-offset-reset: earliest
        enable-auto-commit: false

logging:
  level:
    org.springframework.web: WARN
    com.mint: DEBUG
server:
  port: 8083



