spring:
  application:
    name: cardproducer
    profiles:
      active:
        default

  jpa:
    database: SQL_SERVER
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    datasource:
      url: jdbc:sqlserver://database;databaseName=mint_database
      username: sa
      password: testPassword11
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      initialization-mode: always
      testOnBorrow: true

server:
  port: 8082

  #Setting logging levels
logging:
  level:
    org.springframework.web: WARN
    com.mint: DEBUG

tpd:
  topic-name: com.ng.vela.even.card_verified