spring:
  application:
      name: cardproducer
    profiles:
      active:
        default
  cloud:
    stream:
      bindings:
        output:
            destination:  com.ng.vela.even.card_verified
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost



